linters-settings:
  depguard:
    rules:
      main:
        files:
        - "!**/internal/**/*.go"
        - "!$test"
        allow:
        - $gostd
        - "github.com/editorconfig/editorconfig-core-go/v2"
        - "github.com/hashicorp/go-multierror"
        deny: []
      internal:
        files:
        - "**/internal/**/*.go"
        - "!$test"
        allow:
        - $gostd
        - "github.com/google/go-cmp"
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/editorconfig/editorconfig-core-go)
  cyclop:
    max-complexity: 15
    package-average: 10

linters:
  enable-all: true
  disable:
    - execinquery
    - exhaustruct
    - gomnd
    - tagliatelle
    - typecheck
    - varnamelen
  fast: false
