linters-settings:
  golint:
    min-confidence: 0.3

linters:
  enable:
    - goconst
    - gocyclo
    - goerr113
    - gofmt
    - godox
    - golint
    - gocritic
    - megacheck
    - misspell
    - prealloc
    - unparam
    - scopelint
    - wsl
