linters-settings:
  golint:
    min-confidence: 0.3

linters:
  enable:
    - goconst
    - gofmt
    - golint
    - gocritic
    - megacheck
    - misspell
    - prealloc
    - unparam
    - scopelint
