linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/editorconfig/editorconfig-core-go)
  cyclop:
    max-complexity: 15
    package-average: 10

linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - golint
    - gomnd
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen
  fast: false
