linters-settings:
  gci:
    local-prefixes: github.com/editorconfig/editorconfig-core-go
  cyclop:
    max-complexity: 15
    package-average: 10

linters:
  disable:
    - exhaustivestruct
    - golint
    - gomnd
    - interfacer
    - maligned
    - scopelint
    - tagliatelle
    - varnamelen
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  fast: false
